In [1]:
import tarfile

tar_path = "../data/20_newsgroups.tar.gz"

with tarfile.open(tar_path, "r:gz") as tar:
    tar.extractall("../data")

print("Extracted!")

C:\Users\HP\AppData\Local\Temp\ipykernel_10544\2368260491.py:6: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall("../data")

Extracted!

In [2]:
import tarfile

tar_path = "../data/20_newsgroups.tar.gz"

with tarfile.open(tar_path, "r:gz") as tar:
    tar.extractall("../data")

print("Extracted!")

C:\Users\HP\AppData\Local\Temp\ipykernel_10544\2368260491.py:6: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall("../data")

Extracted!

In [3]:
import os

data_path = "../data/20_newsgroups"

documents = []
labels = []

for category in os.listdir(data_path):

    category_path = os.path.join(data_path, category)

    for file in os.listdir(category_path):

        file_path = os.path.join(category_path, file)

        try:
            with open(file_path, "r", encoding="latin-1") as f:
                text = f.read()

                documents.append(text)
                labels.append(category)

        except:
            continue

print("Documents:", len(documents))

Documents: 19997

In [6]:
import pandas as pd

df = pd.DataFrame({
    "text": documents,
    "label": labels
})

df.head()

                                                text        label
0  Xref: cantaloupe.srv.cs.cmu.edu alt.atheism:49...  alt.atheism
1  Xref: cantaloupe.srv.cs.cmu.edu alt.atheism:51...  alt.atheism
2  Newsgroups: alt.atheism\nPath: cantaloupe.srv....  alt.atheism
3  Xref: cantaloupe.srv.cs.cmu.edu alt.atheism:51...  alt.atheism
4  Xref: cantaloupe.srv.cs.cmu.edu alt.atheism:51...  alt.atheism

In [7]:
import re

def clean_text(text):

    text = re.split(r'\n\s*\n', text, maxsplit=1)
    text = text[1] if len(text) > 1 else text[0]

    text = text.lower()

    text = re.sub(r'\S+@\S+', '', text)
    text = re.sub(r'http\S+', '', text)

    text = re.sub(r'[^a-zA-Z0-9 ]', ' ', text)

    text = re.sub(r'\s+', ' ', text)

    return text.strip()

In [8]:
df["clean_text"] = df["text"].apply(clean_text)

df.head()

,text,label,clean_text
0,Xref: cantaloupe.srv.cs.cmu.edu alt.atheism:49...,alt.atheism,archive name atheism resources alt atheism arc...
1,Xref: cantaloupe.srv.cs.cmu.edu alt.atheism:51...,alt.atheism,archive name atheism introduction alt atheism ...
2,Newsgroups: alt.atheism\nPath: cantaloupe.srv....,alt.atheism,in article charley wingate writes well john ha...
3,Xref: cantaloupe.srv.cs.cmu.edu alt.atheism:51...,alt.atheism,until kings become philosophers or philosopher...
4,Xref: cantaloupe.srv.cs.cmu.edu alt.atheism:51...,alt.atheism,in article bob mcgwier writes 1 however i hate...

In [9]:
df.to_csv("../data/cleaned_newsgroups.csv", index=False)

print("Saved cleaned dataset")

Saved cleaned dataset